# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlAhf0aQZq15OVFFNnPdKM6W3DAZOw-h
"""

import streamlit as st
import numpy as np
import joblib

# LOAD SAVED MODELS (NO TRAINING)
rf_model = joblib.load("rf_model.sav")
knn_model = joblib.load("knn_model.sav")
scaler = joblib.load("scaler.sav")

# PAGE TITLE
st.title("Health Risk Classification")
st.markdown(
    "Predict health risk using **Random Forest** and **KNN** models "
    "based on lifestyle and health factors."
)

# INPUT UI
st.header("Input Health Data")

col1, col2 = st.columns(2)

with col1:
    age = st.slider("Age", 0, 100, 30)
    bmi = st.slider("BMI", 10.0, 50.0, 22.0)
    sleep = st.slider("Sleep (hours)", 0.0, 12.0, 7.0)

with col2:
    smoking = st.selectbox("Smoking", [0, 1])
    alcohol = st.selectbox("Alcohol", [0, 1])
    sugar = st.slider("Sugar Intake", 0.0, 100.0, 30.0)

# PREDICTION
if st.button("Predict Health Risk"):
    input_data = np.array([[age, bmi, smoking, alcohol, sleep, sugar]])

    rf_pred = rf_model.predict(input_data)[0]
    knn_pred = knn_model.predict(scaler.transform(input_data))[0]
    
    st.markdown("""
    **Keterangan:**
    * 0 = High Risk (Risiko Tinggi)
    * 1 = Low Risk (Risiko Rendah)
    """)

    st.subheader("Prediction Result")
    st.write(f"Random Forest: {rf_pred}")
    st.write(f"KNN: {knn_pred}")
