# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlAhf0aQZq15OVFFNnPdKM6W3DAZOw-h
"""

import streamlit as st
import numpy as np
import joblib

# LOAD MODELS
dt_model = joblib.load("dt_best_model.sav")
knn_model = joblib.load("knn_best_model.sav")
scaler = joblib.load("scaler.sav")

# PAGE TITLE
st.title("Health Risk Classification")
st.markdown(
    "Predict health risk using **Decision Tree (Best Model)** and **KNN** "
    "based on lifestyle and health factors."
)

# INPUT UI
st.header("Input Health Data")

col1, col2 = st.columns(2)

with col1:
    st.text("Personal Data")
    age = st.slider("Age", 0, 100, 30)
    bmi = st.slider("BMI", 10.0, 50.0, 22.0)
    sleep = st.slider("Sleep (hours)", 0.0, 12.0, 7.0)

with col2:
    st.text("Lifestyle Habits")
    smoking = st.selectbox("Smoking", [0, 1])
    alcohol = st.selectbox("Alcohol", [0, 1])
    sugar = st.slider("Sugar Intake", 0.0, 100.0, 30.0)

# PREDICTION
st.text("")
if st.button("Predict Health Risk"):
    input_data = np.array([[
        age,
        bmi,
        sleep,
        smoking,
        alcohol,
        sugar
    ]])

    # Decision Tree prediction
    dt_pred = dt_model.predict(input_data)[0]

    # KNN prediction (scaled)
    input_scaled = scaler.transform(input_data)
    knn_pred = knn_model.predict(input_scaled)[0]

    st.subheader("Prediction Result")
    st.write(f"**Decision Tree:** {dt_pred}")
    st.write(f"**KNN:** {knn_pred}")
