# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Con9pkp041UA9AuM2sjzfoiQoBoOeYlQ
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import joblib

df = pd.read_csv("Lifestyle_and_Health_Risk_Prediction_Synthetic_Dataset.csv")

# ---------- OUTLIER HANDLING ----------
numeric_cols = df.select_dtypes(["float64", "int64"]).columns
df_handled = df.copy()

for col in numeric_cols:
    Q1 = df_handled[col].quantile(0.25)
    Q3 = df_handled[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_handled[col] = np.clip(df_handled[col], lower, upper)

# ---------- ENCODING ----------
encoders = {}
cols = ['married','exercise','sugar_intake','alcohol','smoking','profession','health_risk']

for col in cols:
    le = LabelEncoder()
    df_handled[col] = le.fit_transform(df_handled[col])
    encoders[col] = le

# ---------- FEATURES ----------
X = df_handled[['age','bmi','smoking','alcohol','sleep','sugar_intake']]
y = df_handled['health_risk']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# ---------- MODELS ----------
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# ---------- SAVE ----------
joblib.dump(rf, "rf_model.sav")
joblib.dump(knn, "knn_model.sav")
joblib.dump(scaler, "scaler.sav")
joblib.dump(encoders, "encoders.sav")